include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - invalid_case_patterns
    - one_member_abstracts
    - only_throw_errors
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - prefer_collection_literals
    - prefer_spread_collections
    - unnecessary_new
    - prefer_mixin
    - always_use_package_imports
    - directives_ordering
    - avoid_redundant_argument_values
    - avoid_escaping_inner_quotes
    - avoid_init_to_null
    - avoid_positional_boolean_parameters
    - avoid_unnecessary_containers
    - avoid_void_async
    - prefer_if_null_operators
